---
apiVersion: example.com/v1
kind: MyThing
metadata:
  name: my-thing
spec: {}
---
apiVersion: example.com/v1
kind: MyThingConfig
metadata:
  name: config-a
spec:
  myThingRef: my-thing
---
apiVersion: example.com/v1
kind: MyThingConfig
metadata:
  name: config-b
spec:
  myThingRef: my-thing
